export const CONVERSATION_LIST_REQUEST = 'CONVERSATION_LIST_REQUEST';
export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_LIST_SUCCESS';
export const CONVERSATION_LIST_FAIL = 'CONVERSATION_LIST_FAIL';

export const CONVERSATION_DETAIL_REQUEST = 'CONVERSATION_DETAIL_REQUEST';
export const CONVERSATION_DETAIL_SUCCESS = 'CONVERSATION_DETAIL_SUCCESS';
export const CONVERSATION_DETAIL_FAIL = 'CONVERSATION_DETAIL_FAIL';

export const CONVERSATION_SET_ACTIVE = 'CONVERSATION_SET_ACTIVE';
export const CONVERSATION_CLEAR_ACTIVE = 'CONVERSATION_CLEAR_ACTIVE';
